package com.donHub.donHub.model;

public enum Category {
	
	EDUCATIONAL_MATERIALS,
	ELECTRONICS_AND_GADGETS,
	FURNITURE_AND_HOME_ESSENTIALS,
	CLOTHINGS_AND_ACCESSORIES,
	TRANSPORTATION,
	MUSICAL_INSTRUMENTS,
	FREEBIES,
	DIYS,
	MISCELLANEOUS,
	HEALTH,
	ENTERTAINMENT
	}
